<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-N6UCNFO" name="com.aspire.selenium.TestNG.AssertClass1" tests="7" failures="1" timestamp="2022-02-26T10:57:51 IST" time="0.000" errors="0">
  <testcase name="m4" time="0.000" classname="com.aspire.selenium.TestNG.AssertClass1"/>
  <system-out/>
  <testcase name="m6" time="0.000" classname="com.aspire.selenium.TestNG.AssertClass1"/>
  <system-out/>
  <testcase name="m2" time="0.000" classname="com.aspire.selenium.TestNG.AssertClass1"/>
  <system-out/>
  <testcase name="m3" time="0.000" classname="com.aspire.selenium.TestNG.AssertClass1"/>
  <system-out/>
  <testcase name="m1" time="0.000" classname="com.aspire.selenium.TestNG.AssertClass1"/>
  <system-out/>
  <testcase name="m7" time="0.000" classname="com.aspire.selenium.TestNG.AssertClass1">
    <failure type="java.lang.AssertionError" message="Fail This Test Case intentionally">
      <![CDATA[java.lang.AssertionError: Fail This Test Case intentionally
at org.testng.Assert.fail(Assert.java:99)
at com.aspire.selenium.TestNG.AssertClass1.m7(AssertClass1.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- m7 -->
  <system-out/>
  <testcase name="m5" time="0.000" classname="com.aspire.selenium.TestNG.AssertClass1"/>
  <system-out/>
</testsuite> <!-- com.aspire.selenium.TestNG.AssertClass1 -->
